---
- name: Install required packages
  pkgng:
    name:
      - drm-kmod
      - gnome-lite
      - gnome-terminal
      - libva-utils
      - mesa-dri
      - urwfonts
      - xorg
      - xwayland
    state: present
  tags: ['pkg', 'gnome']

# pw groupmod video -m $USER
- name: Add user to video group
  user:
    name: "{{ target_user }}"
    groups: video
    append: yes
  tags: ['gnome']

- name: Configure boot loader for Gnome
  lineinfile:
    path: /boot/loader.conf
    line: "{{ item.line }}"
  loop:
    - line: utouch_load="YES"
  when: ansible_virtualization_type == 'kvm'
  tags: ['config']

- name: Configure services for Gnome
  lineinfile:
    path: /etc/rc.conf
    line: "{{ item.line }}"
  loop:
    - line: dbus_enable="YES"
    - line: gdm_enable="YES"
    - line: var_run_enable="YES"
  tags: ['gnome']

# For UEFI. For BIOS use VESA
- name: Configure SCFB
  copy:
    src: 20-scfb.conf
    dest: /usr/local/etc/X11/xorg.conf.d/20-scfb.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['gnome']

- name: Configure fonts
  copy:
    src: 90-fonts.conf
    dest: /usr/local/etc/X11/xorg.conf.d/90-fonts.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['gnome']

- name: Mount /var/run if not mounted
  mount:
    path: /var/run
    src: tmpfs
    fstype: tmpfs
    state: mounted
  tags: ['mount', 'gnome']
