---
- name: Install required packages
  pkgng:
    name:
      - drm-kmod
      - gnome-lite
      - libva-intel-driver 
      - mesa-dri
    state: present
  tags: ['pkg', 'gnome']

- name: Add user to video group
  user:
    name: ricardo
    groups: video
    append: yes
  tags: ['gnome']

- name: Configure boot loader for Gnome
  lineinfile:
    path: /boot/loader.conf
    line: "{{ item.line }}"
  loop:
    - line: utouch_load="YES"
  tags: ['config']

- name: Configure services for Gnome
  lineinfile:
    path: /etc/rc.conf
    line: "{{ item.line }}"
  loop:
    - line: dbus_enable="YES"
    - line: gdm_enable="YES"
    - line: var_run_enable="YES"
  tags: ['gnome']
