---
- name: Install required packages
  pkgng:
    name:
      - drm-kmod
      - gnome-lite
      - gnome-terminal
      - libva-utils
      - mesa-dri
      - urwfonts
      - xorg
      - xwayland
    state: present

# pw groupmod video -m $USER
- name: Add user to video group
  user:
    name: "{{ target_user }}"
    groups: video
    append: yes

- name: Configure boot loader for Gnome
  lineinfile:
    path: /boot/loader.conf.d/utouch.conf
    line: utouch_load="YES"
    create: true
  when: ansible_virtualization_type == 'kvm'

- name: Configure DBus
  lineinfile:
    path: /etc/rc.conf.d/dbus
    line: dbus_enable="YES"
    create: true

- name: Configure GDM
  lineinfile:
    path: /etc/rc.conf.d/gdm
    line: gdm_enable="YES"
    create: true

- name: Enable /var/run
  lineinfile:
    path: /etc/rc.conf.d/var_run
    line: var_run_enable="YES"
    create: true

# For UEFI. For BIOS use VESA
- name: Configure SCFB
  copy:
    src: 20-scfb.conf
    dest: /usr/local/etc/X11/xorg.conf.d/20-scfb.conf
    owner: root
    group: wheel
    mode: 0644

- name: Configure fonts
  copy:
    src: 90-fonts.conf
    dest: /usr/local/etc/X11/xorg.conf.d/90-fonts.conf
    owner: root
    group: wheel
    mode: 0644

- name: Mount /var/run if not mounted
  mount:
    path: /var/run
    src: tmpfs
    fstype: tmpfs
    state: mounted
