---
- name: Install Intel packages
  pkgng:
    name:
      - libva-intel-driver 
    state: present

- name: Configure /etc/rc.conf for i915
  lineinfile:
    path: /etc/rc.conf
    line: "{{ item.line }}"
  loop:
    - line: 'kld_list="i915kms"'

- name: Add Intel to PORTS_MODULES
  lineinfile:
    path: /etc/make.conf
    line: 'PORTS_MODULES+= graphics/drm-kmod graphics/gpu-firmware-intel-kmod'
    state: present
