---
- name: Enable linux binary compatibility
  lineinfile:
    path: /etc/rc.conf
    line: "linux_enable=\"YES\""
  tags: ['linux']

# zfs create -o mountpoint=/compat/linux zroot/linux
- name: Create ZFS dataset for linux
  zfs:
    name: zroot/linux
    state: present
    extra_zfs_properties:
      mountpoint: /compat/linux
  tags: ['linux, 'zfs']

- name: Start linux service
  shell: service linux start
  args:
    creates: /compat/linux
  tags: ['linux']

- name: Create /etc/resolv.conf
  shell: cp /etc/resolv.conf /compat/linux/etc/resolv.conf
  args:
    creates: /compat/linux/etc/resolv.conf
  tags: ['linux']

# Note: Mounted by default by linux service
#- name: Mount /compat/linux/proc
#  mount:
#    path: /compat/linux/proc
#    src: linprocfs
#    fstype: linprocfs
#    state: mounted
#  tags: ['linux', 'mount']

# Note: Mounted by default by linux service
#- name: Mount /compat/linux/sys
#  mount:
#    path: /compat/linux/sys
#    src: linsysfs
#    fstype: linsysfs
#    state: mounted
#  tags: ['linux', 'mount']

# Note: Mounted by default by linux service
#- name: Mount /compat/linux/dev
#  mount:
#    path: /compat/linux/dev
#    src: devfs
#    fstype: devfs
#    state: mounted
#  tags: ['linux', 'mount']

# Note: Mounted by default by linux service
#- name: Mount /compat/linux/dev/fd
#  mount:
#    path: /compat/linux/dev/fd
#    src: fdescfs
#    fstype: fdescfs
#    state: mounted
#    opts: rw,linrdlnk
#  tags: ['linux', 'mount']

# Note: Mounted by default by linux service
#- name: Mount /compat/linux/dev/shm
#  mount:
#    path: /compat/linux/dev/shm
#    src: tmpfs
#    fstype: tmpfs
#    state: mounted
#  tags: ['linux', 'mount']

- name: Install required packages
  pkgng:
    name:
      - debootstrap
      - linux_base-rl9
      - linux-rl9-brotli
      - linux-rl9-ca-certificates
      - linux-rl9-curl
      - linux-rl9-libevent
      - linux-rl9-libsigsegv
    state: present
  tags: ['pkg', 'linux']

# Uncomment and add the mounts above for Ubuntu chroot on FreeBSD
#- name: Create Ubuntu debootstrap
#  shell: debootstrap jammy /compat/ubuntu
#  args:
#    creates: /compat/ubuntu
#  tags: ['linux']
