---
- name: Enable linux binary compatibility
  lineinfile:
    path: /etc/rc.conf
    line: "linux_enable=\"YES\""
  tags: ['linux']

- name: Start linux service
  shell: service linux start
  args:
    creates: /compat/linux

- name: Install required packages
  pkgng:
    name:
      - debootstrap
      - linux_base-c7
    state: present
  tags: ['pkg']
