---
- include_tasks: pkg.yml
- include_tasks: ssh.yml
- include_tasks: config.yml
- include_tasks: pf.yml
- include_tasks: linux.yml
- include_tasks: src.yml
- include_tasks: security.yml
- include_tasks: user.yml
- include_tasks: podman.yml
- include_tasks: firmware.yml
  when: ansible_virtualization_type != 'kvm'
- include_tasks: mitigations.yml
  when: ansible_virtualization_type == 'kvm'
- include_tasks: qemu.yml
  when: ansible_virtualization_type == 'kvm'
- include_tasks: golang.yml
