---
# https://wiki.freebsd.org/PkgBase

- name: Backup libraries
  lineinfile:
    path: /usr/local/etc/pkg.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - line: BACKUP_LIBRARIES=true
      regexp: ^BACKUP_LIBRARIES=
    - line: BACKUP_LIBRARY_PATH=/usr/local/lib/compat/pkg
      regexp: ^BACKUP_LIBRARY_PATH=

- name: Configure pkgbase repo
  copy:
    src: FreeBSD-base.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD-base.conf
    owner: root
    group: wheel
    mode: 0600

- name: Install FreeBSD base packages
  pkgng:
    name:
      #- FreeBSD-acct
      - FreeBSD-acpi
      - FreeBSD-at
      #- FreeBSD-autofs
      #- FreeBSD-bhyve
      #- FreeBSD-bluetooth
      - FreeBSD-bootloader
      - FreeBSD-bsdinstall
      #- FreeBSD-bsnmp
      - FreeBSD-caroot
      #- FreeBSD-ccdconfig
      #- FreeBSD-certctl
      - FreeBSD-clang
      - FreeBSD-console-tools
      #- FreeBSD-csh
      - FreeBSD-ctf-tools
      #- FreeBSD-cxgbe-tools
      - FreeBSD-dhclient
      #- FreeBSD-dma
      #- FreeBSD-dpv
      - FreeBSD-dtrace
      - FreeBSD-dwatch
      #- FreeBSD-ee
      - FreeBSD-efi-tools
      - FreeBSD-elftoolchain
      - FreeBSD-fetch
      #- FreeBSD-ftp
      #- FreeBSD-ftpd
      - FreeBSD-fwget
      - FreeBSD-games
      - FreeBSD-geom
      #- FreeBSD-ggate
      #- FreeBSD-hast
      - FreeBSD-hostapd
      #- FreeBSD-hyperv-tools
      #- FreeBSD-inetd
      #- FreeBSD-ipf
      #- FreeBSD-ipfilter
      #- FreeBSD-ipfw
      #- FreeBSD-iscsi
      - FreeBSD-jail
      #- FreeBSD-kerberos
      - FreeBSD-kernel-generic
      #- FreeBSD-kernel-minimal
      - FreeBSD-lld
      - FreeBSD-lldb
      - FreeBSD-locales
      #- FreeBSD-mlx-tools
      - FreeBSD-mtree
      #- FreeBSD-natd
      #- FreeBSD-netmap
      - FreeBSD-newsyslog
      - FreeBSD-nfs
      - FreeBSD-nvme-tools
      - FreeBSD-openssl
      - FreeBSD-periodic
      - FreeBSD-pf
      - FreeBSD-pkg-bootstrap
      #- FreeBSD-ppp
      - FreeBSD-quotacheck
      - FreeBSD-rc
      - FreeBSD-rcmds
      - FreeBSD-rdma
      - FreeBSD-rescue
      - FreeBSD-resolvconf
      - FreeBSD-runtime
      #- FreeBSD-sendmail
      - FreeBSD-smbutils
      - FreeBSD-ssh
      - FreeBSD-syscons
      - FreeBSD-syslogd
      #- FreeBSD-tcpd
      #- FreeBSD-telnet
      #- FreeBSD-tests
      - FreeBSD-ufs
      - FreeBSD-unbound
      - FreeBSD-utilities
      - FreeBSD-vi
      - FreeBSD-vt-data
      - FreeBSD-wpa
      #- FreeBSD-yp
      - FreeBSD-zfs
      - FreeBSD-zoneinfo
    state: present

