---
- name: Set /root/.gitconfig
  copy:
    src: gitconfig
    dest: /root/.gitconfig
    owner: root
    group: wheel
    mode: 0644
  tags: ['root']

- name: Make vim work
  copy:
    src: vimrc
    dest: /root/.vimrc
    owner: root
    group: wheel
    mode: 0644
  tags: ['root']
