---
- name: Security sysctls
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - line: security.bsd.see_other_uids=0
      regexp: ^security\.bsd\.see_other_uids
    - line: security.bsd.see_other_gids=0
      regexp: ^security\.bsd\.see_other_gids
    - line: security.bsd.see_jail_proc=0
      regexp: ^security\.bsd\.see_jail_proc
    - line: security.bsd.unprivileged_read_msgbuf=0
      regexp: ^security\.bsd\.unprivileged_read_msgbuf
    - line: security.bsd.unprivileged_proc_debug=0
      regexp: ^security\.bsd\.unprivileged_proc_debug
    - line: kern.randompid=1
      regexp: ^kern\.randompid
