---
- name: Security sysctl's
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: security.bsd.see_other_uids
      value: 0
    - name: security.bsd.see_other_gids
      value: 0
    - name: security.bsd.see_jail_proc
      value: 0
    - name: security.bsd.unprivileged_read_msgbuf
      value: 0
    - name: security.bsd.unprivileged_proc_debug
      value: 0
    - name: net.inet.ip.process_options
      value: 0
    - name: net.inet.ip.random_id
      value: 1
    - name: net.inet.tcp.drop_synfin
      value: 1
    - name: kern.coredump
      value: 0
    - name: security.bsd.hardlink_check_gid
      value: 1
    - name: security.bsd.hardlink_check_uid
      value: 1

# This one should be specified with lineinfile because
# it returns a random value when reading the sysctl
- name: More security sysctls
  lineinfile:
    path: /etc/sysctl.conf
    line: kern.randompid=1
    regexp: ^kern\.randompid

- name: Security sysctl's in loader.conf
  lineinfile:
    path: /boot/loader.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - line: security.bsd.allow_destructive_dtrace=0
      regexp: ^security\.bsd\.allow_destructive_dtrace=

- name: Install security packages
  pkgng:
    name:
      - doas
      - sudo
    state: present

- name: Configure doas
  copy:
    src: doas.conf
    dest: /usr/local/etc/doas.conf
    owner: root
    group: wheel
    mode: 0600

- name: Configure sudo
  copy:
    src: sudoers.d/custom
    dest: /usr/local/etc/sudoers.d/custom
    owner: root
    group: wheel
    mode: 0600

- name: Turn off suid/sgid bits
  file:
    path: "{{ item.path }}"
    mode: "u-s,g-s"
  ignore_errors: yes
  loop:
    - path: /usr/bin/lpq
    - path: /usr/bin/lpr
    - path: /usr/bin/lprm
    - path: /usr/sbin/lpc
