---
- name: Security sysctl's
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: security.bsd.see_other_uids
      value: 0
    - name: security.bsd.see_other_gids
      value: 0
    - name: security.bsd.see_jail_proc
      value: 0
    - name: security.bsd.unprivileged_read_msgbuf
      value: 0
    - name: security.bsd.unprivileged_proc_debug
      value: 0
  tags: ['security']

# This one should be specified with lineinfile because
# it returns a random value when reading the sysctl
- name: More security sysctls
  lineinfile:
    path: /etc/sysctl.conf
    line: kern.randompid=1
    regexp: ^kern\.randompid

- name: Security sysctl's in loader.conf
  lineinfile:
    path: /boot/loader.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - line: security.bsd.allow_destructive_dtrace=0
      regexp: ^security\.bsd\.allow_destructive_dtrace=
  tags: ['security']

- name: Install security packages
  pkgng:
    name:
      - doas
      - sudo
    state: present
  tags: ['pkg', 'security']

- name: Configure doas
  copy:
    src: doas.conf
    dest: /usr/local/etc/doas.conf
    owner: root
    group: wheel
    mode: 0600
  tags: ['security']

- name: Create sudo group
  group:
    name: sudo
    system: true
  tags: ['security']

- name: Allow users in groups sudo & wheel to run sudo
  copy:
    src: sudoers.d/custom
    dest: /usr/local/etc/sudoers.d/custom
    owner: root
    group: wheel
    mode: 0600
  tags: ['security']
