---
#- name: Add src collection
#  shell: git clone --depth 1 --branch stable/14 https://github.com/freebsd/freebsd-src /usr/src
#  args:
#    creates: /usr/src
#  tags: ['src']

#- name: Add src collection
#  git:
#    repo: https://git.FreeBSD.org/src.git
#    dest: /usr/src
#    depth: 1
#    version: stable/14
#  tags: ['src']

- name: Copy /etc/make.conf
  copy:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['src']

- name: Copy /etc/src.conf
  copy:
    src: src.conf
    dest: /etc/src.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['src']

#- name: Copy CUSTOM kernel configuration
#  copy:
#    src: CUSTOM
#    dest: /usr/src/sys/amd64/conf/CUSTOM
#    owner: root
#    group: wheel
#    mode: 0644
#  tags: ['src']
