---
#- name: Add src collection
#  git:
#    repo: https://git.FreeBSD.org/src.git
#    dest: /usr/src
#    depth: 1
#    version: stable/14
#  tags: ['src']

- name: Copy /etc/make.conf
  copy:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644

- name: Copy CUSTOM kernel configuration
  copy:
    src: CUSTOM
    dest: /usr/src/sys/amd64/conf/CUSTOM
#    owner: root
#    group: wheel
    mode: 0644
