---
- name: Add user to needed groups
  user:
    name: "{{ target_user }}"
    groups: wheel,operator
    append: yes
    shell: /usr/local/bin/bash

- name: Fix HOME permissions
  file:
    path: "/home/{{ target_user }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0750'

- name: User sysctl's
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: vfs.usermount
      value: 1
