---
- name: Add user to needed groups
  user:
    name: ricardo
    groups: wheel,sudo,operator
    append: yes
    shell: /usr/local/bin/bash
  tags: ['user']

- name: Fix HOME permissions
  file:
    path: /home/ricardo
    state: directory
    owner: ricardo
    group: ricardo
    mode: '0750'
  tags: ['user']

- name: User sysctl's
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: vfs.usermount
      value: 1
  tags: ['user', 'sysctl']
